openapi: 3.0.3
info:
  title: Argent Bank API
  description: API permettant la gestion des utilisateurs et transactions.
  version: 1.2.0

servers:
  - url: http://localhost:3001/api/v1

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /user/login:
    post:
      summary: Login user
      description: Authentifie l'utilisateur et retourne un token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Succès de la connexion
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Identifiants incorrects

  /user/logout:
    get:
      summary: Logout user
      description: Déconnecte l'utilisateur.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Déconnexion réussie

  /user/profile:
    get:
      summary: Get user profile
      description: Récupère les informations du profil de l'utilisateur connecté.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Profil utilisateur récupéré
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
        "401":
          description: Token invalide ou absent

    put:
      summary: Update user profile
      description: Met à jour les informations du profil utilisateur.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: "Nouveau nom d'utilisateur"
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        "200":
          description: Profil utilisateur mis à jour
        "400":
          description: Requête invalide
        "401":
          description: Token invalide ou absent

  /transactions:
    get:
      summary: Get user's transactions
      description: Récupère la liste des transactions de l'utilisateur connecté.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Liste des transactions récupérée
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    date:
                      type: string
                      format: date
                    amount:
                      type: number
                    description:
                      type: string
                    category:
                      type: string
                    note:
                      type: string
        "401":
          description: Token invalide ou absent

  /transactions/{transactionId}:
    get:
      summary: Get transaction details
      description: Récupère les détails d'une transaction spécifique.
      security:
        - bearerAuth: []
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Détails de la transaction récupérés
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  date:
                    type: string
                    format: date
                  amount:
                    type: number
                  description:
                    type: string
                  category:
                    type: string
                  note:
                    type: string
        "404":
          description: Transaction non trouvée
        "401":
          description: Token invalide ou absent

    put:
      summary: Update a transaction
      description: Modifie certaines informations d'une transaction (catégorie, note).
      security:
        - bearerAuth: []
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                note:
                  type: string
      responses:
        "200":
          description: Transaction mise à jour
        "400":
          description: Requête invalide
        "404":
          description: Transaction non trouvée
        "401":
          description: Token invalide ou absent
