openapi: 3.0.3
info:
  title: Argent Bank API
  description: API pour gérer les comptes bancaires et transactions des utilisateurs.
  version: 2.0.0

servers:
  - url: http://localhost:3001/api/v1

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /accounts:
    get:
      summary: Get user accounts
      description: Récupère la liste des comptes bancaires de l'utilisateur connecté.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Liste des comptes récupérée
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    accountId:
                      type: string
                    accountType:
                      type: string
                      enum: [Checking, Savings, Credit]
                    balance:
                      type: number
        "401":
          description: Token invalide ou absent

  /accounts/{accountId}/transactions:
    get:
      summary: Get account transactions
      description: Récupère la liste des transactions associées à un compte spécifique.
      security:
        - bearerAuth: []
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Liste des transactions récupérée
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transactionId:
                      type: string
                    date:
                      type: string
                      format: date
                    amount:
                      type: number
                    description:
                      type: string
                    category:
                      type: string
                    note:
                      type: string
        "401":
          description: Token invalide ou absent
        "404":
          description: Compte non trouvé

  /transactions/{transactionId}:
    get:
      summary: Get transaction details
      description: Récupère les détails d'une transaction spécifique.
      security:
        - bearerAuth: []
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Détails de la transaction récupérés
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactionId:
                    type: string
                  date:
                    type: string
                    format: date
                  amount:
                    type: number
                  description:
                    type: string
                  category:
                    type: string
                  note:
                    type: string
        "404":
          description: Transaction non trouvée
        "401":
          description: Token invalide ou absent

    put:
      summary: Update a transaction
      description: Modifie certaines informations d'une transaction (catégorie, note).
      security:
        - bearerAuth: []
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                note:
                  type: string
      responses:
        "200":
          description: Transaction mise à jour
        "400":
          description: Requête invalide
        "404":
          description: Transaction non trouvée
        "401":
          description: Token invalide ou absent
